name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - main
    - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --hook-stage manual --all-files

  checks-linux:
    name: Check Python ${{ matrix.python-version }} on ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install compiler tools on macOS
      if: runner.os == 'macOS'
      run: brew install make automake swig gmp mpfr boost

    - name: Install extra deps on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libboost-dev libmpfr-dev swig autoconf libtool

    - name: Install package
      run: python -m pip install '.[test]' -v

    - name: Test package
      run: python -m pytest -vv -rs -Wd

  checks-macOS:
    name: Check Python ${{ matrix.python-version }} on macOS-11
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install compiler tools on macOS
      if: runner.os == 'macOS'
      run: brew install make automake swig gmp mpfr boost

    - name: Install extra deps on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libboost-dev libmpfr-dev swig autoconf libtool

    - name: Install package
      run: python -m pip install '.[test]' -v
      env: 
        MACOSX_DEPLOYMENT_TARGET: "10.14"

    - name: Test package
      run: python -m pytest -vv -rs -Wd


  test_wheels_linux:
    name: Wheel on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_ARCHS: auto64
        CIBW_BUILD: cp311-*
        CIBW_BUILD_VERBOSITY: 2

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

  test_wheels_macOS:
    name: Wheel on macOS
    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_ARCHS: auto64
        CIBW_BUILD: cp311-*
        CIBW_BUILD_VERBOSITY: 2
        MACOSX_DEPLOYMENT_TARGET: "10.14"

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

  pass:
    needs: [pre-commit, checks-linux, checks-macOS, test_wheels_linux, test_wheels_macOS]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All jobs passed"
